languageCode = "en-us"
title = "Dental Stories"
baseURL = "https://rach1997.github.io/dental-stories-blog/"
theme = "hugo-html5up-alpha"

[params]
description = "Dental Stories - Quick shorts of advice that make you better"
# images = ["images/pic01.jpg"]
copyright = "© Rachana Chitalkar. All rights reserved."
design = "Design: [HTML5 UP](http://html5up.net/)"
mainSections = ["blog"]

### Footer Social Media Links ###
[[params.share]]
title = "facebook"
icon = "fa-facebook-f" # fontawesome icons https://fontawesome.com/icons?d=gallery&s=brands
link = "https://www.facebook.com/rachana.chitalkar.3"

[[params.share]]
title = "twitter"
icon = "fa-twitter"
link = "https://twitter.com/ChtlkrRac"

[[params.share]]
title = "linkedin"
icon = "fa-linkedin"
link = "https://www.linkedin.com/in/dr-rachana-chitalkar-a18253195/"

[[params.share]]
title = "instagram"
icon = "fa-instagram"
link = "https://www.instagram.com/rachanachitalkar"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 20
